auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Songtao's Blog”
title: 凉凉夜色为你思念成河
description: Everything about Songtao.
url: http://www.steff720.com
feed: /atom.xml
#author_info: <a href="http://mukosame.github.io/">Mukosame</a>
